server {
    listen 80;
    listen [::]:80;

    server_name katakata.local;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name katakata.local;

    ssl_certificate     /Users/Will/Sites/katakata/config/nginx/ssl/katakata.local.crt;
    ssl_certificate_key /Users/Will/Sites/katakata/config/nginx/ssl/katakata.local.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers on;

    root /Users/Will/Sites/katakata/public;
    index index.php index.html;

    charset utf-8;

    access_log /opt/homebrew/var/log/nginx/katakata.access.log;
    error_log  /opt/homebrew/var/log/nginx/katakata.error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;

        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    location ~* \.(?:css|js|jpg|jpeg|png|gif|webp|svg|ico|woff|woff2|ttf|map)$ {
        expires 7d;
        access_log off;
        try_files $uri =404;
    }
}
