server {
    listen 80;
    listen [::]:80;

    server_name katakata.local;

    root /Users/Will/Sites/katakata/public;
    index index.php index.html;

    charset utf-8;

    access_log /opt/homebrew/var/log/nginx/katakata.access.log;
    error_log  /opt/homebrew/var/log/nginx/katakata.error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;

        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    location ~* \.(?:css|js|jpg|jpeg|png|gif|webp|svg|ico|woff|woff2|ttf|map)$ {
        expires 7d;
        access_log off;
        try_files $uri =404;
    }
}